import SideBar from '@/components/ui/SideBarComponent';
import './globals.css';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import { QueryClient } from '@tanstack/react-query';
import { Toaster } from 'react-hot-toast';
import Providers from '@/utils/Providers';
import { HeaderComponent } from '@/components/ui/HeaderComponent';
import { DarkModeProvider } from '../components/shared/Context/DarkModeContext';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

// const queryClient = new QueryClient({
// 	defaultOptions: {
// 		queries: { staleTime: 60 * 1000 }
// 	}
// });
export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${raleway.className} min-h-screen`}>
				{/* <section className="flex  gap-3">
					<section className="w-1/4">
						<SideBar />
					</section>

					<section className="w-3/4">
						<h1>Header</h1>

						{children}
					</section>
				</section> */}

				{/* <HeaderComponent /> */}
				<Providers>
					<DarkModeProvider>{children}</DarkModeProvider>
				</Providers>

				<Toaster
					position="top-center"
					gutter={12}
					containerStyle={{ margin: '8px' }}
					toastOptions={{
						success: { duration: 3000 },
						error: { duration: 3000 },
						style: {
							fontSize: '16px',
							maxWidth: '500px',
							padding: '16px 24px'
						}
					}}
				/>
			</body>
		</html>
	);
}
