import SideBar from '@/components/ui/SideBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <section className="flex  gap-3">
					<section className="w-1/4">
						<SideBar />
					</section>

					<section className="w-3/4">
						<h1>Header</h1>

						{children}
					</section>
				</section> */}
				{children}
			</body>
		</html>
	);
}
